const main = async (schema, data) => {
    try {
        // Si falla esta validaci√≥n, pasa al catch
        await schema.validateAsync(data)
    } catch (error) {
        
    }
}